### ISSUE TITLE
Empty loop files

### ISSUE THREAD

**Issue by ahmedabbas81** [PouletAxel/SIP#10]
Dear all,
I run the following command:

`java -jar SIP_HiC_v1.6.1.jar hic /fastscratch/ahmed/human/young_male/Juicer_home/aligned/inter_30.hic hg19.chrom.sizes ./young_male_sip /fastscratch/ahmed/human/young_male/Juicer_home/scripts/juicer_tools.jar`

I get errors like this:

```
start dump chrX size 155270560 res 5kb
start dump chrX size 155270560 dump chrX:0:9999999 res 5kb
Exception in thread "pool-1-thread-4" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at process.DumpData.observedMExpected(DumpData.java:109)
	at process.DumpData.dumpObservedMExpected(DumpData.java:85)
	at multiProcesing.RunnableDumpDataHiC.run(RunnableDumpDataHiC.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

and get empty output file like this
![image](https://user-images.githubusercontent.com/32098502/107268510-3bcc4680-6a16-11eb-9dac-04ba67ab6642.png)

Any suggestions please?

Thank you

**Comment by PouletAxel** [comment]
Dear,
Are you using the same chr size file used to make the hic file?
Axel

**Comment by ahmedabbas81** [comment]
Hi,
I didn't use chr size file to get the hic file.
I used the same reference files as here
https://github.com/aidenlab/juicer/wiki/Installation

Thank you

**Comment by PouletAxel** [comment]
How did you make the hic file?
I think the problem is, the program tries to dump some data not existing in
your hic file.

**Comment by ahmedabbas81** [comment]
I am using Juicer, and using the genome id: hg19. In this case, it is not required to put chrom.sizes path

Thanks

**Comment by PouletAxel** [comment]
Ok great,
Can you share with your hic file? I need to test what is wrong.
my private email address is pouletaxel@gmail.com

Best
Axel

**Comment by ahmedabbas81** [comment]
Thank you. I tried with another slightly older version of Juicer tools and it worked. Thank you

**Comment by PouletAxel** [comment]
Great, 
could you send me the 2 first lines of your chr size file please.
Did you use the latest juicer version when SIP failed?

**Comment by ahmedabbas81** [comment]
sorry for the late answer. Yes the latest version of juicer failed. I will send you the two lines. Thanks

**Comment by PouletAxel** [comment]
Ok thanks.
I need to document it so thanks to catch it.
