### ISSUE TITLE
coolTools path

### ISSUE THREAD

**Issue by gdolsten** [PouletAxel/SIP#11]
Hi, when we are using SIP, how are we supposed to provide the path to cooler? Is it just the directory containing cooler? 
Right now I am running: 

java -jar ~/SIP/SIP_HiC.jar cool data.mcool chrom.sizes sip_loops.txt ~/cools/cooltools ~/cools/cooler  

But I get the following error:
Cannot run program "/Genomics/grid/users/gdolsten/cools/cooltools": error=13, Permission denied

cools/cooltools looks like: 
balance.py  cli  contrast.py  coverage.py  directionality.py  dotfinder.py  eigdecomp.py  expected.py  __init__.py  insulation.py  io  lib  __main__.py  __pycache__  saddle.py  sample.py  snipping.py

**Comment by PouletAxel** [comment]
Hi,
your cooler and cooltools are not directory but binary file,
on my laptop for example: ~/anaconda3/bin/cooler

**Comment by gdolsten** [comment]
Thank you, my concerns are answered

**Comment by PouletAxel** [comment]
java -jar SIP_HiC.jar cool ~/Desktop/SIP/testCooler/4DNFIWO9BDFZ.mcool hg38.sizes ~/Desktop/Cool/ ~/anaconda3/bin/cooltools ~/anaconda3/bin/cooler -g 1.5 -mat 2000 -d 5 -res 5000 -t 2000 -cpu 3

you can choose you resolution with -res
