### ISSUE TITLE
interchromosomal peak calling

### ISSUE THREAD

**Issue by jazberna1** [PouletAxel/SIP#12]
Hello SIP developers,

This is not an issue. I just would like to ask you if SIP is able to call interchromosomal loops.

Thanks
Jorge

**Comment by jordrow** [comment]
SIP does not currently call inter-chromosomal loops. However, we are currently thinking about it and we're doing some preliminary tests to see how feasible it would be. We can send you an update once we have a working version.

**Comment by jazberna1** [comment]
Hi,

Yes please, I would be very interested.

Thanks so much
Jorge
