### ISSUE TITLE
Image processing isolates loop, but some of them not called.

### ISSUE THREAD

**Issue by gdolsten** [PouletAxel/SIP#14]
Hey, here is an image of how a Hi-C matrix looks post-image-processing: (I removed the diagonal for visualization purposes).

![image](https://user-images.githubusercontent.com/78431504/108557653-e706b680-72c6-11eb-9834-0105cac990da.png)

It calls most of the loops, but it misses the prominent loop in the top-left...Do you know why this loop is not being called? It seems quite prominent so I was wondering which parameters could be changed to find it. Is it just too large for the loop-calling program?

These loops were called with the following parameters: -res 1000 -d 10 -fdr .1 -del false -nbZero 10 -mat 500 -t 1000

**Comment by PouletAxel** [comment]
Hi,
Can you send us the command line please?

**Comment by gdolsten** [comment]
The parameters were as follows: 
 -res 1000 -d 10 -fdr .1 -del false -nbZero 10 -mat 500 -t 1000

**Comment by PouletAxel** [comment]
Can you send me the .tif corresponding to this image please?

**Comment by gdolsten** [comment]
Do you want the one that is _N, that is _processed, or the one without any of these?

**Comment by PouletAxel** [comment]
You can send me the three of them via my email (pouletaxel@gmail.com)
