### ISSUE TITLE
java OutOfBoundsException error

### ISSUE THREAD

**Issue by NMaziak** [PouletAxel/SIP#22]
Hello, 

I'm running into an issue when running SIP (and I do apologize in case the problem is right in face and I just can't seem to catch it). 

When I run the following: 
`java -jar ../SIP_HiCv1.6.2.jar cool cooler_files/sample_200bp.mcool chrom.sizes.all SIP_loops ../../Python_env/bin/cooltools  ../../Python_env/bin/cooler -isDroso false -res 400 -factor 4 -t 2000 -fdr 0.1 -d 6 -mat 5000 -nbZero 6 -del true -cpu 15 -g 1.5 -min 2 -max 2`

I get the following warning for Numba and a java OutOfBoundsException error: 

```
/Python_env/lib/python3.8/site-packages/cooltools/lib/numutils.py:652: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def iterative_correction_symmetric(
Python_env/lib/python3.8/site-packages/cooltools/lib/numutils.py:727: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def iterative_correction_asymmetric(x, max_iter=1000, tol=1e-5, verbose=False):

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 1
        at sipMain.Hic_main.testTools(Hic_main.java:486)
        at sipMain.Hic_main.main(Hic_main.java:263)

```

Would you happen to know if the warning is causing the issue (and in that case do I need to put no python for numba.jit)? Or is it something else? I'm not computationally trained   - so again sorry in case this is straight-forward. 

For reference, the versions are:
cooltools, version 0.5.4
cooler, version 0.9.2

I also tried lowering the versions like here but this did not resolve anything. 
https://github.com/PouletAxel/SIP/issues/15

Thanks again and I appreciate all the help!

**Comment by PouletAxel** [comment]
Hi,
Sorry for the late answer.

Can you try to run it with: -res 400 -mat 5000 -f 1?
Do you obtain teh same error?

Thanks
Axel

**Comment by NMaziak** [comment]
Hi Axel, I tried just now but I still get the same error but a slightly different line: 
```
java -jar ../SIP_HiCv1.6.2.jar cool cooler_files/NC14_200bp.mcool chrom.sizes.all SIP_loops/ ../../Public_env/bin/cooltools ../../Python_env/bin/cooler -res 400 -mat 5000 -factor 1 -mat 5000
cooltools, version 0.5.4
/Python_env/lib/python3.8/site-packages/cooltools/lib/numutils.py:652: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def iterative_correction_symmetric(
/Python_env/lib/python3.8/site-packages/cooltools/lib/numutils.py:727: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def iterative_correction_asymmetric(x, max_iter=1000, tol=1e-5, verbose=False):

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 1
        at plop.sipMain.Hic_main.testTools(Hic_main.java:487)
        at plop.sipMain.Hic_main.main(Hic_main.java:264)
```

**Comment by PouletAxel** [comment]
Ok,
Are you able to dump the data with cooltools from your data whithout using
SIP?
The first error is due to the cooler and cooltools that I am using to dum
and read the mcool matrix.

**Comment by NMaziak** [comment]
Hi Axel, 

When I ran 
`cooler dump -t chroms NC14_100bp.mcool::/resolutions/200` 

It gave me the following:
```
2L      23513712
2R      25286936
3L      28110227
3R      32079331
4       1348131
X       23542271
Y       3667352
```

This also matches my chrom.sizes file. So it should be working no?

**Comment by PouletAxel** [comment]
It should be working for sure.
is it ok for you to share with me your data.
I want to reproduce the same error on my computer and track it?

Thanks

**Comment by NMaziak** [comment]
Hi Axel, the issue seems to have been having numba version 0.57.0 (the warning being thrown), I downgraded to 0.50.0 and SIP is finally working :) 

My lab-mate pointed out that it might be SIP's handling of the warning thrown by Numba that is the problem. 

Thank you so much for all the help!

**Comment by PouletAxel** [comment]
You are correct.Sip is catching the warning I think.
 I will correct that
Thanks for catching it.
Axel

**Comment by NMaziak** [comment]
Thank you for this tool!
