### ISSUE TITLE
Doesn't produce any Result!!!!

### ISSUE THREAD

**Issue by hmamohit** [PouletAxel/SIP#23]
I used GM12878 primary MAPQ 30 dataset in .hic format.

My cmd
`java -jar SIP_HiC_v1.6.1.jar hic /home/ubuntu/loop_analyzer/data/GSE63525_GM12878_insitu_primary_30.hic /home/ubuntu/loop_analyzer/data/hg19.chrom.sizes /home/ubuntu/loop_analyzer/data/sip /home/ubuntu/loop_analyzer/data/juicer_tools_1.22.01.jar -cpu 7 -res 5000 -t 9000`

It doesn't produce any results. I attached the full log here > [log.txt](https://github.com/PouletAxel/SIP/files/12152726/log.txt)

Could you please help me running this. Thanks.

**Comment by shadhinaust** [comment]
[log.txt](https://github.com/PouletAxel/SIP/files/12152725/log.txt)

**Comment by PouletAxel** [comment]
it could be two things I think.
the version of juicer you are using behave weirdly so we advised to use Juicer Tools v1.13 instead (we put this information here : [(https://github.com/PouletAxel/SIP]) in the readme).

The chromosome name between your HiC file and the hg19.chrom.sizes are different.

**Comment by hmamohit** [comment]
It works. Thanks
