### ISSUE TITLE
-factor option

### ISSUE THREAD

**Issue by Kurotakid** [PouletAxel/SIP#4]
Hi,
I performed the SIP with "-factor" option using my hic file. However, an error has occurred as follows:
```
java -jar SIP_HiC.jar hic cDC1_trimmed.hic chrom.size.mm10.txt Output4/ /home/kurotaki/juicer/scripts/common/juicer_tools.jar -res 5000 -factor 4 -cpu 10
-factor doesn't existed
```
When I did this analysis without "-factor" option, I could get a result.
I'd appreciate it if you help me.
Best,

**Comment by jordrow** [comment]
Currently the -factor option is unavailable while we work out a few kinks. In the meantime you can achieve the same results by running SIP for each desired resolution separately.

**Comment by Kurotakid** [comment]
Thanks.
