### ISSUE TITLE
Failed to load hic file from web address.

### ISSUE THREAD

**Issue by yang-kaist** [PouletAxel/SIP#5]
Hi,

I tried to use SIP with in-situ Hi-C data from Rao's paper (GSE63525).
The size of .hic file is huge, and I tried to use web address of t hem.
(According to the manual, "web address to the .hic file can be used.")

I used following command to call chromatin loop.
`  java -jar SIP_HiC_1.5.1.jar hic https://hicfiles.s3.amazonaws.com/hiseq/imr90/in-situ/combined.hic ChromInfo.txt gm_sip juicer_tools_1.19.02.jar  `
And I found following error messages.

` https://hicfiles.s3.amazonaws.com/hiseq/gm12878/in-situ/combined_30.hic doesn't existed !!! `

I also tested whether URL is invalid or juicer tools is malfunctioning by dump contact matrix with following command.
` java -jar juicer_tools_1.19.02.jar  dump oe KR https://hicfiles.s3.amazonaws.com/hiseq/imr90/in-situ/combined.hic 10 10 BP 5000 `

ps : My goal is to retrieve chromatin loops of 7 human cell lines from Rao's paper.
Figure 2.F of your paper suggest that you already called loop of them.
So it would be helpful if you release the chromatin loops.

Sincerely,
Yang

**Comment by PouletAxel** [comment]
Hi Yang,
Thanks for pointing that.
I corrected that in the newest version of SIP (1.5.4).
test it, it working in my environment, so if you of some error tell me
Thanks
Axel

**Comment by yang-kaist** [comment]
Hi Axel,

Thank you for rapid response!
I'm testing recent version, and it starts to dump the matrix from URL.

ps : By the way, dumping matrix from URL or download hic file takes too long time.
Would you mind to share the loops from Rao's dataset? (which were used for comparison with HICCUPS)

Sincerely, 
Yang

**Comment by PouletAxel** [comment]
Hi Yang 
I upload the loop computed for the compiraison.
Best
Axel
[GM12878_SIPloops.txt](https://github.com/PouletAxel/SIP/files/4506569/GM12878_SIPloops.txt)
[HELALoops.txt](https://github.com/PouletAxel/SIP/files/4506570/HELALoops.txt)
[HMECLoops.txt](https://github.com/PouletAxel/SIP/files/4506571/HMECLoops.txt)
[HUVECLoops.txt](https://github.com/PouletAxel/SIP/files/4506572/HUVECLoops.txt)
[IMR90Loops.txt](https://github.com/PouletAxel/SIP/files/4506573/IMR90Loops.txt)
[K562Loops.txt](https://github.com/PouletAxel/SIP/files/4506574/K562Loops.txt)
[KBM7Loops.txt](https://github.com/PouletAxel/SIP/files/4506575/KBM7Loops.txt)
[NHEKLoops.txt](https://github.com/PouletAxel/SIP/files/4506576/NHEKLoops.txt)
