### ISSUE TITLE
fail to read hic file

### ISSUE THREAD

**Issue by xiaowenchenjax** [PouletAxel/SIP#6]
Hi,
I used the command line to run HIC file
java -jar /home/c-chenx/SIP_HiC_v1.5/SIP_HiC.jar hic /projects/li-lab/chenx/hic/juicer_mm/juicer_mm_TET2_wt1/aligned/inter_30.hic /home/c-chenx/juicer/references/mm10.chrom.sizes /projects/li-lab/chenx/hic/juicer_mm/juicer_mm_TET2_wt1/aligned/inter_30_loops /home/c-chenx/juicer/scripts/juicer_tools.jar
but there is an error:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at sipMain.Hic_main.readChrSizeFile(Hic_main.java:277)
	at sipMain.Hic_main.main(Hic_main.java:209)

Could you give me some suggestion? Thank you

**Comment by jordrow** [comment]
It sounds like there is an issue reading in your chromosome size file. Can you paste the contents of the size file that you are using?

**Comment by PouletAxel** [comment]
Can you run it with the last version please and tell me if you have the same error please?
[here](https://github.com/PouletAxel/SIP/releases/tag/SIP_HiC_v1.6)

**Comment by xiaowenchenjax** [comment]
1.6 version ？




| |
Xiaowen Chen
|
|
邮箱：hrbmucxw@163.com
|

Signature is customized by Netease Mail Master

On 04/20/2020 21:50, PouletAxel wrote:

Can you run it with the last version please and tell me if you have the same error please?
here

**Comment by PouletAxel** [comment]
yes

**Comment by xiaowenchenjax** [comment]
sure!
















在 2020-04-21 09:50:50，"PouletAxel" <notifications@github.com> 写道：

Can you run it with the last version please and tell me if you have the same error please?
here

**Comment by PouletAxel** [comment]
And send me then the command line you are running and the error if you still have the error please

**Comment by xiaowenchenjax** [comment]
Hi, 
still same error.

java -jar /home/c-chenx/script/SIP-SIP_HiC_v1.6/SIP_HiC_v1.6.jar hic /projects/li-lab/chenx/hic/juicer_mm/juicer_mm_TET2_wt1/aligned/inter_30.hic /home/c-chenx/juicer/references/mm10.chrom.sizes /projects/li-lab/chenx/hic/juicer_mm/juicer_mm_TET2_wt1/aligned/inter_30_loops /home/c-chenx/juicer/scripts/juicer_tools.jar

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1

at sipMain.Hic_main.readChrSizeFile(Hic_main.java:336)

at sipMain.Hic_main.main(Hic_main.java:231)













At 2020-04-21 09:54:57, "PouletAxel" <notifications@github.com> wrote:

And send me then the command line you are running and the error if you still have the error please

**Comment by PouletAxel** [comment]
Can you test with the file join :
[mm10.chrom.sizes.txt](https://github.com/PouletAxel/SIP/files/4507261/mm10.chrom.sizes.txt)

**Comment by xiaowenchenjax** [comment]
It is running, what you change to make it work? Do i need to dump the hic file, if it is created from juicer pipeline?
Thank you!!
















At 2020-04-21 10:08:10, "PouletAxel" <notifications@github.com> wrote:

Can you test with the file join :
mm10.chrom.sizes.txt

**Comment by PouletAxel** [comment]
it is because you have some spaces and not tabulation in your chr file:
between the name of chr and the size you one tabulation and not several spaces.

Yes because SIP i doing some computation to obtain the value and work with them.
When you have run one time SIP after you can use the processed command to refine the other parameter and refine the detection of loop

Thanks
And thanks to use SIP
