### ISSUE TITLE
cooler and cooltools version tests fail

### ISSUE THREAD

**Issue by adadiehl** [PouletAxel/SIP#8]
Please see command and output...

```
java -jar /data/software/SIP/SIP_HiC_v1.6.1.jar cool data/matrix/GM12878_NlaIII_native_20190805_5566f_guppy_3.4.8hac_GRCh38_bwa_0.7.17_sensitive.matrix.balanced.mcool /data/genomes/hg38/hg38.chrom.sizes loops/ /home/adadiehl/.conda/envs/cooler_env/bin/cooler /home/adadiehl/.conda/envs/cooler_env/bin/cooltools -cpu 12 
cooler, version 0.8.10
cooltools, version 0.4.0.dev0
/home/adadiehl/.conda/envs/cooler_env/bin/cooler or/home/adadiehl/.conda/envs/cooler_env/bin/cooltools is not the good version for SIP (it needs cooltools version >= 0.3.0 and cooler version >= 0.8.6) !!!” 
```

**Comment by PouletAxel** [comment]
Hi,
It is because you are using a dev version for cooltools.
 I will add something to take the dev  version, in the same time can you try to change your version of cooltools to have a stale version?
thanks
axel

**Comment by PouletAxel** [comment]
Hi,
the command line is
java -jar SIP_HiC.jar cool mcoolFile chrSizeFile Output cooltoolsPath coolerPath options

in your command line you put cooler before cooltools, if you change the order it will work,
Best
Axel

**Comment by adadiehl** [comment]
Thank you for the quick responses! Fixing the order of cooltools and cooler
in the args, as per your suggestion, fixed the problem. This was after I
switched to a non-dev version of cooltools, so don't know if the
non-numeric version number is still an issue, but it's probably worth
mentioning that the first legacy version I installed with pip had a
non-numeric suffix also. This is apparently something their development
team likes to do. Sounds like you're fixing that, though.
Cheers,
Adam

**Comment by PouletAxel** [comment]
Cool thanks
Axel
